// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdlZpKezkvXEM3P8MzS0TLUmu0UHP6h1Y',
    appId: '1:82465206848:android:5ab5d7bc782c77f4c565a5',
    messagingSenderId: '82465206848',
    projectId: 'delivery-service-85ecc',
    databaseURL: 'https://delivery-service-85ecc-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-service-85ecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAigNYUTrVblsXP2Qmz5O5w6mpjlLIoBE4',
    appId: '1:82465206848:ios:f200ba6b955d6009c565a5',
    messagingSenderId: '82465206848',
    projectId: 'delivery-service-85ecc',
    databaseURL: 'https://delivery-service-85ecc-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-service-85ecc.appspot.com',
    iosClientId: '82465206848-tf7eicq7fitl16td7mnlr9ieaug0ubci.apps.googleusercontent.com',
    iosBundleId: 'com.example.backgroundlocator',
  );
}
